### ISSUE TITLE
Code up ctf/9 LFI (lfi.js)

### ISSUE THREAD

**Issue by ponga2112** [ponga2112/websec-ctf-for-n00bs#12]

**Comment by c-h-a-n-c-e** [comment]
Pushed a functional skeleton commit (tied into point system, navs to next challenge). Code recycle of Jason's browser sim window and purge of content. Bare-bones summary page copied.

TODO: Fill in browser sim with LFI content, replace multiple choice questions with relevant content, and fill in the `correct answer summary page` with educational content.

**Comment by c-h-a-n-c-e** [comment]
Finished TODO list from above, ready to ship out as a functional first draft
