### ISSUE TITLE
Phase 2: Proof Reading

### ISSUE THREAD

**Issue by ponga2112** [ponga2112/websec-ctf-for-n00bs#13]
Go thru entire site, correcting for typos, grammar, etc

**Comment by c-h-a-n-c-e** [comment]
Pushed updates that included typo corrections, occasional sentence structure re-writes, a bit of Q&A structuring on the main intro page. Need to make another full pass-through to make sure nothing was missed. After last pass-through will be closing this ticket.

**Comment by c-h-a-n-c-e** [comment]
Made another full pass through the application for typos (good thing, found a bunch). Because I found so many missed typos on this pass through, I'm keeping ticket open until I do another.

**Comment by c-h-a-n-c-e** [comment]
COMPLETED: Go through all answer modals to check for new lines that break text a bit

**Comment by c-h-a-n-c-e** [comment]
Closing out ticket after most recent proof read commit
