### ISSUE TITLE
Phase 3: Functional Testing (Multiuser)

### ISSUE THREAD

**Issue by ponga2112** [ponga2112/websec-ctf-for-n00bs#22]
Another round of functional testing in a multi-user (API-enabled) environment.

**Comment by c-h-a-n-c-e** [comment]
When leaderboard data exists, a new user (no cookies) on the introduction page will see 'undefined' when clicking leaderboard.

![image](https://user-images.githubusercontent.com/30713148/99433309-95671e00-28ca-11eb-9faa-8467a5487bfd.png)

**Comment by c-h-a-n-c-e** [comment]
Fix looks awesome. Noticed that offline leaderboard looks great too, not sure if that was part of this fix or not but regardless calling this done.

![image](https://user-images.githubusercontent.com/30713148/99479060-bf443300-2912-11eb-9aa2-1a970121128f.png)

**Comment by c-h-a-n-c-e** [comment]
Requests to ../api/leaders return the FULL database of users, instead of just the top leaderboard users. This does not scale and should be addressed.

![image](https://user-images.githubusercontent.com/30713148/99482854-20bbd000-291a-11eb-975e-8ac4036a0d37.png)

**Comment by ponga2112** [comment]
changed leaderboard query to: include ``` LIMIT 100```

**Comment by c-h-a-n-c-e** [comment]
Last issue fixed, closing ticket!
